### PR TITLE
miette error diagnostics

### PR DESCRIPTION
**Pull request by JasmineLowen**
This pull request:

- factors out all the custom error types into a new error module
- implements help diagnostics for said errors
- sets up the main app to make it ready to render the miette errors
- does some custom displaying of the miette errors in case the user
  chose the repl mode
- converts some std error types in the one shot mode for compatibility
  reasons

This can be used to implement more detailed errors in the future since it'll
support things like source spans to point to the error locations.

Feel free to suggest better help diagnostics btw! 🙈

### CODE REVIEW

**Review by slotThe — COMMENTED** [review]
It just occured to me—and I should have really thought of this yesterday, sorry—that we already depend on a diagnostics library: [ariadne](https://crates.io/crates/ariadne)! I guess one should at least *try* to use that one first, before taking on 30 new dependencies :)

**Comment by JasmineLowen** [comment]
Makes sense! I'm closing this here in favor of the new idea then

**Comment by slotThe** [comment]
This was just meant as something to think about—I didn't want to discourage this PR in any way :)

**Comment by JasmineLowen** [comment]
I'm not discouraged :p It's more like a nerd snipe because now I want to cut down the dependency tree a bit more. I'm thinking about how we could use `winnow` as a parser and still get nice error messages by using `ariadne`. I thought the nice errors were deeply integrated with `chumsky` but this separation is neat.

**Pull request closed without merging**
